// Note: This file only works if you have the "REST Client" extension in Visual Studio Code.
// Each request most be separated by ###
// A blank line must be between any headers and the body of the request

###
// This is the registration request.
POST https://127.0.0.1:8443/api/users/_register HTTP/1.1
content-type: application/json

{
  "name": "base",
  "email": "base@outlook.com",
  "password": "123"
}

###
// Log the user into the system.
// The user name and password will be verified.
// If this cannot be verified the response will be "bad-request".
POST https://127.0.0.1:8443/api/users/_login HTTP/1.1
content-type: application/json

{
  "name": "some_one",
  "password": "password1"
}

###
// Log the user into the system.
// The user name and password will be verified.
// If this cannot be verified the response will be "bad-request".
POST https://127.0.0.1:8443/api/users/_login HTTP/1.1
content-type: application/json

{
  "name": "base",
  "password": "123"
}

###
// Change the password of the current user
PUT https://127.0.0.1:8443/api/users/_change_pwd HTTP/1.1
content-type: application/json

{
  "oldPassword": "password1",
  "newPassword": "password2"
}

###
// Get a list of all of the users.
GET https://127.0.0.1:8443/api/users HTTP/1.1
content-type: application/json

###
// Hit the index of the api (this is in the users controller because this is an example application.)
GET https://127.0.0.1:8443/api/users/me HTTP/1.1
content-type: application/json

###
// Log the user out of the system. This will remove the cookie from the session.
POST https://127.0.0.1:8443/api/users/_logout HTTP/1.1
content-type: application/json

###
// Get a list of all recipe categories.
GET https://127.0.0.1:8443/api/category HTTP/1.1
content-type: application/json

###
// Get a list of all shared recipes.
GET https://127.0.0.1:8443/api/recipe HTTP/1.1
content-type: application/json

###
// Gets the highest level of authorization for the current user.
GET https://127.0.0.1:8443/api/authorization HTTP/1.1
content-type: application/json

###
// POSTS a new root-level category into the system
POST https://127.0.0.1:8443/api/category HTTP/1.1
content-type: application/json

{
  "name": "some_cool_name",
  "parentCategoryId": null
}

###
// Puts an updated name for a root-level category
PUT https://127.0.0.1:8443/api/category/26 HTTP/1.1
content-type: application/json

{
  "name": "carbs",
  "parentCategoryId": 29
}

###
// Deletes an existing root-level category
DELETE https://127.0.0.1:8443/api/category/29 HTTP/1.1
content-type: application/json
